"use server";

import { revalidatePath } from "next/cache";
import { requireSession } from "@/lib/route-guard";
import { purchasePackage } from "@/lib/investments";

export type PurchaseActionResult =
  | { ok: true }
  | { ok: false; errorKey: "errorInsufficientFunds" | "errorPackageUnavailable" | "errorGeneric" };

/**
 * Server action behind the purchase confirmation dialog. The acting user is
 * always resolved from the request's own session cookie — never a
 * client-supplied id (invariant #9). idempotencyKey is generated by the
 * client once per confirm click and passed through unchanged so a retried
 * submit (e.g. a double-click before the button disables) collapses to the
 * same purchasePackage call.
 */
export async function purchasePackageAction(
  packageId: string,
  idempotencyKey: string,
  locale: string,
): Promise<PurchaseActionResult> {
  const user = await requireSession(new Date());

  try {
    await purchasePackage(user.id, { packageId, forDate: new Date(), idempotencyKey });
    // Wallet B balance and the purchasable-package list are read fresh by the
    // server component on every render, but Next won't re-run it just because
    // this action wrote to the DB — the client would otherwise keep showing
    // the pre-purchase props until a manual reload. Revalidating this exact
    // path forces the next render of /[locale]/packages to refetch.
    revalidatePath(`/${locale}/packages`);
    return { ok: true };
  } catch (err) {
    const message = err instanceof Error ? err.message : "";
    if (/insufficient/i.test(message)) {
      return { ok: false, errorKey: "errorInsufficientFunds" };
    }
    if (/deactivated|not found/i.test(message)) {
      return { ok: false, errorKey: "errorPackageUnavailable" };
    }
    return { ok: false, errorKey: "errorGeneric" };
  }
}
