-- CreateTable
-- Monthly Rank Volume: total investment volume generated by a user's DIRECT
-- referrals' own purchases only (depth = 1, sponsor tree — never the
-- placement tree). Resets every calendar month (no carry forward): `month`
-- is a fresh "YYYY-MM" key (Asia/Dubai), so a new month is always a new row.
-- `qualified_direct_referrals` is written by the monthly rank-evaluation job
-- (a later ticket) — this migration only supports incremental accrual of
-- `volume` at purchase time.
CREATE TABLE "mrv_periods" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "month" TEXT NOT NULL,
    "volume" DECIMAL(24,8) NOT NULL DEFAULT 0,
    "qualified_direct_referrals" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "mrv_periods_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "mrv_periods" ADD CONSTRAINT "mrv_periods_user_id_fkey"
  FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- CreateIndex
CREATE UNIQUE INDEX "mrv_periods_user_id_month_key"
  ON "mrv_periods" ("user_id", "month");
